language: python
cache: pip

branches:
  except:
      - /^[^/]+/.+$/

python:
  - "2.7"
  - "pypy"
  - "pypy3"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
    include:
        - python: "3.7"
          dist: xenial

install:
  - travis_retry pip install --upgrade setuptools pip codecov
  - pip install -e '.[development]'

script:
    python setup.py test

after_script:
    bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    channels:
      - 'irc.freenode.org#webcore'
    use_notice: true
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository_slug}:%{branch}@%{commit} %{message}"
      - "Duration: %{duration} - Details: %{build_url}"

